<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>WuPause</AssemblyName>
    <RootNamespace>WuPause</RootNamespace>
    <LangVersion>7.3</LangVersion>
    <Nullable>disable</Nullable>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <DebugType>none</DebugType>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
    <AutoGenerateBindingRedirects>false</AutoGenerateBindingRedirects>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Product>Windows Update Pause Tool</Product>
    <AssemblyTitle>Windows 更新暂停工具</AssemblyTitle>
    <NoWarn>CS1591</NoWarn>
  </PropertyGroup>
</Project>